image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y gcc g++
  - apt-get install -y libboost-all-dev
  - apt-get install -y libprotobuf-dev protobuf-compiler
  - apt-get install -y cmake
  - g++ --version
  - cmake --version
  - dpkg -s libboost-dev | grep 'Version'
  - dpkg -s libprotobuf-dev | grep 'Version'


compile:
  script:
  - chmod +x build.sh
  - ./build.sh