language: cpp
compiler: gcc
os: linux

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo apt install -y libprotobuf-dev protobuf-compiler
  - mkdir -p $HOME/.cache
  - touch $HOME/.cache/mydependency.so


script: ./build.sh