language: cpp
compiler: gcc
os: linux

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo apt install -y libprotobuf-dev protobuf-compiler

script:
  - chmod +x build.sh
  - ./build.sh