language: cpp
dist: xenial
sudo: true
compiler: gcc

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5

script: 
  - g++ -o simple_client simple_client.cpp -lboost_system -std=c++11
  - g++ -o simple_server simple_server.cpp -lboost_system -lboost_thread -std=c++11