language: cpp
dist: xenial
sudo: true
compiler: gcc

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo apt install -y libprotobuf-dev protobuf-compiler
  - g++ --version
  - dpkg -s libboost-dev | grep 'Version'
  - echo "Install setup completed"

script:
  - protoc -I=. --cpp_out=. message.proto
  - g++ -o simple_client simple_client.cpp message.pb.cc -lboost_system -lboost_thread -lprotobuf -std=c++11
  - g++ -o simple_server simple_server.cpp message.pb.cc -lboost_system -lboost_thread -lprotobuf -std=c++11